create table if not exists categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_category_name ON categories(LOWER(name));