CREATE SCHEMA IF NOT EXISTS category_schema;

CREATE TABLE IF NOT EXISTS category_schema.categories
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_category_name
    ON category_schema.categories(LOWER(name));