CREATE SCHEMA IF NOT EXISTS comment_schema;

-- Таблица комментариев
CREATE TABLE IF NOT EXISTS comment_schema.comments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    message VARCHAR(2000) NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_comments_event_id ON comment_schema.comments(event_id);
CREATE INDEX IF NOT EXISTS idx_comments_user_id ON comment_schema.comments(user_id);
CREATE INDEX IF NOT EXISTS idx_comments_created ON comment_schema.comments(created);