create table if not exists users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email VARCHAR(254) NOT NULL,
    name VARCHAR(250) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE UNIQUE INDEX IF NOT EXISTS idx_user_email ON users(email);