-- Таблица событий
CREATE TABLE IF NOT EXISTS events
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    annotation VARCHAR(2000) NOT NULL,
    category_id BIGINT NOT NULL,
    confirmed_requests BIGINT DEFAULT 0,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator_id BIGINT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    participant_limit BIGINT DEFAULT 0,
    published_on TIMESTAMP WITHOUT TIME ZONE,
    request_moderation BOOLEAN DEFAULT TRUE,
    state VARCHAR(50) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views BIGINT DEFAULT 0
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_events_category_id ON events(category_id);
CREATE INDEX IF NOT EXISTS idx_events_initiator_id ON events(initiator_id);
CREATE INDEX IF NOT EXISTS idx_events_state ON events(state);
CREATE INDEX IF NOT EXISTS idx_events_event_date ON events(event_date);
CREATE INDEX IF NOT EXISTS idx_events_views ON events(views);
CREATE INDEX IF NOT EXISTS idx_events_location ON events(lat, lon);

-- Ограничения
ALTER TABLE events ADD CONSTRAINT chk_event_date_future
    CHECK (event_date > created_on);
ALTER TABLE events ADD CONSTRAINT chk_participant_limit_non_negative
    CHECK (participant_limit >= 0);
ALTER TABLE events ADD CONSTRAINT chk_confirmed_requests_non_negative
    CHECK (confirmed_requests >= 0);
ALTER TABLE events ADD CONSTRAINT chk_views_non_negative
    CHECK (views >= 0);