CREATE SCHEMA IF NOT EXISTS compilation_schema;

CREATE TABLE IF NOT EXISTS compilation_schema.compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
    );

CREATE TABLE IF NOT EXISTS compilation_schema.compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
    );