DROP TABLE IF EXISTS events;

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
    );

DROP TABLE IF EXISTS events_compilations;

CREATE TABLE IF NOT EXISTS compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,

    CONSTRAINT fk_compilation
    FOREIGN KEY (compilation_id)
    REFERENCES compilations(id)
    ON DELETE CASCADE,

    CONSTRAINT pk_compilation_events
    PRIMARY KEY (compilation_id, event_id)
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_compilations_title ON compilations(title);
CREATE INDEX IF NOT EXISTS idx_compilation_events_compilation_id
    ON compilation_events(compilation_id);
CREATE INDEX IF NOT EXISTS idx_compilation_events_event_id
    ON compilation_events(event_id);