-- Таблица событий
CREATE TABLE IF NOT EXISTS events
(
    id BIGINT PRIMARY KEY,
    title VARCHAR(120) NOT NULL,
    annotation VARCHAR(2000) NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    paid BOOLEAN DEFAULT FALSE,
    state VARCHAR(50) NOT NULL
    );

-- Таблица подборок
CREATE TABLE IF NOT EXISTS compilations
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(50) NOT NULL,
    pinned BOOLEAN DEFAULT FALSE
    );

-- Связующая таблица
CREATE TABLE IF NOT EXISTS events_compilations
(
    compilation_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,

    CONSTRAINT fk_compilation FOREIGN KEY (compilation_id) REFERENCES compilations(id) ON DELETE CASCADE,
    CONSTRAINT fk_event FOREIGN KEY (event_id) REFERENCES events(id) ON DELETE CASCADE,
    CONSTRAINT pk_events_compilations PRIMARY KEY (compilation_id, event_id)
    );

-- Индексы
CREATE INDEX IF NOT EXISTS idx_compilations_title ON compilations(title);
CREATE INDEX IF NOT EXISTS idx_events_compilations_compilation_id ON events_compilations(compilation_id);
CREATE INDEX IF NOT EXISTS idx_events_compilations_event_id ON events_compilations(event_id);